### ISSUE TITLE
Not checking if allowed to start service

### ISSUE THREAD

**Issue by frmz** [chrislacy/ActionLauncherApi#8]
When publishing current state the api is not checking if the service is currently allowed to start foreground services, a live wallpaper most of the times is not, i get quite a lot of errors due to this:

`Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.actionlauncher.api.action.PUBLISH_UPDATE cmp=com.actionlauncher.playstore/com.actionlauncher.wallpaperstate.LiveWallpaperSourceSubscriber (has extras) }: app is in background uid UidRecord{b1c38b9 u0a157 TPSL idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
       at android.app.ContextImpl.startService(ContextImpl.java:1532)
       at android.content.ContextWrapper.startService(ContextWrapper.java:664)
       at com.actionlauncher.api.LiveWallpaperSource.publishCurrentState(LiveWallpaperSource.java:339)
       at com.actionlauncher.api.LiveWallpaperSource.processAndDispatchSubscriberAdded(LiveWallpaperSource.java:307)
       at com.actionlauncher.api.LiveWallpaperSource.processSubscribe(LiveWallpaperSource.java:283)
       at com.actionlauncher.api.LiveWallpaperSource.onHandleIntent(LiveWallpaperSource.java:225)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by devilshezi0** [comment]
> When publishing current state the api is not checking if the service is currently allowed to start foreground services, a live wallpaper most of the times is not, i get quite a lot of errors due to this:
> 
> `Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.actionlauncher.api.action.PUBLISH_UPDATE cmp=com.actionlauncher.playstore/com.actionlauncher.wallpaperstate.LiveWallpaperSourceSubscriber (has extras) }: app is in background uid UidRecord{b1c38b9 u0a157 TPSL idle procs:1 seq(0,0,0)}
>        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
>        at android.app.ContextImpl.startService(ContextImpl.java:1532)
>        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
>        at com.actionlauncher.api.LiveWallpaperSource.publishCurrentState(LiveWallpaperSource.java:339)
>        at com.actionlauncher.api.LiveWallpaperSource.processAndDispatchSubscriberAdded(LiveWallpaperSource.java:307)
>        at com.actionlauncher.api.LiveWallpaperSource.processSubscribe(LiveWallpaperSource.java:283)
>        at com.actionlauncher.api.LiveWallpaperSource.onHandleIntent(LiveWallpaperSource.java:225)
>        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loop(Looper.java:193)
>        at android.os.HandlerThread.run(HandlerThread.java:65)`
